### ISSUE TITLE
Add button to open google maps for a specific route

### ISSUE THREAD

**Issue by SeanHoude** [Teamalpha/Stumbl#10]
(DESTINATION IN ADDRESS FORM)
https://www.google.com/maps/dir/?api=1&destination=760+West+Genesee+Street+Syracuse+NY+13204

(DEST IN LAT/LON FORM)
https://www.google.com/maps/dir/?api=1&destination=43.12345,-76.12345

ADD THIS TO THE END OF THE URL:
&travelmode=walking

**Comment by stevelknievel** [comment]
Taken from
http://gearside.com/easily-link-to-locations-and-directions-using-the-new-google-maps/

Directions (detect user’s current location as starting point)
By simply including “Current Location” in the starting point input field, Google will detect the user’s location and automatically generate directions based on where they are right now. The string “My Location” can also work, but “Current Location” seems to have a higher success rate.

Primary method?

https://www.google.com/maps/dir/?api=1&destination=760+West+Genesee+Street+Syracuse+NY+13204

Note: As commenters have pointed out, translate “Current+Location” into your applicable language.

Another method:
https://www.google.com/maps/dir/Current+Location/760+West+Genesee+Street+Syracuse+NY+13204

Another:
https://maps.google.com?saddr=Current+Location&daddr=760+West+Genesee+Street+Syracuse+NY+13204
