### ISSUE TITLE
default to walking mode

### ISSUE THREAD

**Issue by SeanHoude** [Teamalpha/Stumbl#16]
Intersting article on URLs and how Google encodes them to determine transportation preferences (walk, bike, public transpo, car), etc.  

https://webapps.stackexchange.com/questions/67190/how-can-i-encode-my-preference-of-biking-walking-public-transport-in-a-google-ma#comment67171_79544

**Comment by stevelknievel** [comment]
Intersting article on URLs and how Google encodes them to determine transportation preferences (walk, bike, public transpo, car), etc.

https://webapps.stackexchange.com/questions/67190/how-can-i-encode-my-preference-of-biking-walking-public-transport-in-a-google-ma#comment67171_79544
