### ISSUE TITLE
show distance from destination

### ISSUE THREAD

**Issue by SeanHoude** [Teamalpha/Stumbl#8]
Distance Matrix API:
https://developers.google.com/maps/documentation/distance-matrix/start

Requesting Distance Data for Different Travel Modes (set to default to walking):
https://developers.google.com/maps/documentation/distance-matrix/intro#travel_modes

Google Distance Matrix Documentation:
https://developers.google.com/maps/documentation/javascript/distancematrix

** be sure to see info about indicating travel mode as "walking"

**Comment by stevelknievel** [comment]
https://developers.google.com/maps/documentation/javascript/distancematrix

Info on using the Google Distance Matrix
